---
name: CI
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - uses: 8398a7/action-slack@v2.3.0
        with:
          status: ${{ job.status }}
          author_name: Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
